import { intToRoman } from "../src/integer-to-roman";

describe("Integer to Roman", () => {
  it.each([
    { num: 0 , result: "" },
    { num: 1 , result: "I" },
    { num: 2 , result: "II" },
    { num: 3 , result: "III" },
    { num: 4 , result: "IV" },
    { num: 5 , result: "V" },
    { num: 6 , result: "VI" },
    { num: 7 , result: "VII" },
    { num: 8 , result: "VIII" },
    { num: 9 , result: "IX" },
    { num: 10 , result: "X" },
    { num: 11 , result: "XI" },
    { num: 12 , result: "XII" },
    { num: 13 , result: "XIII" },
    { num: 14 , result: "XIV" },
    { num: 15 , result: "XV" },
    { num: 16 , result: "XVI" },
    { num: 19 , result: "XIX" },
    { num: 20 , result: "XX" },
    { num: 21 , result: "XXI" },
    { num: 24 , result: "XXIV" },
    { num: 25 , result: "XXV" },
    { num: 26 , result: "XXVI" },
    { num: 30 , result: "XXX" },
    { num: 35 , result: "XXXV" },
    { num: 40 , result: "XL" },
    { num: 41 , result: "XLI" },
    { num: 45 , result: "XLV" },
    { num: 49 , result: "XLIX" },
    { num: 50 , result: "L" },
    { num: 51 , result: "LI" },
    { num: 90 , result: "XC" },
    { num: 91 , result: "XCI" },
    { num: 100 , result: "C" },
    { num: 101 , result: "CI" },
    { num: 151 , result: "CLI" },
    { num: 500 , result: "D" },
    { num: 501 , result: "DI" },
    { num: 601 , result: "DCI" },
    { num: 1601 , result: "MDCI" },
    { num: 4000 , result: "" },
    { num: 3749 , result: "MMMDCCXLIX" },
    { num: 58 , result: "LVIII" },
    { num: 1994 , result: "MCMXCIV" },
    { num: 60 , result: "LX" },
  ])("should pass $num  $result", async ({ num, result }) => {
    expect(intToRoman(num)).toStrictEqual(result);
  });
});
