import { romanToInt } from "../src/roman-to-integer";

describe("Integer to Roman", () => {
  it.each([
    { result: 0 , s: "" },
    { result: 1 , s: "I" },
    { result: 2 , s: "II" },
    { result: 3 , s: "III" },
    { result: 4 , s: "IV" },
    { result: 5 , s: "V" },
    { result: 6 , s: "VI" },
    { result: 7 , s: "VII" },
    { result: 8 , s: "VIII" },
    { result: 9 , s: "IX" },
    { result: 10 , s: "X" },
    { result: 11 , s: "XI" },
    { result: 12 , s: "XII" },
    { result: 13 , s: "XIII" },
    { result: 14 , s: "XIV" },
    { result: 15 , s: "XV" },
    { result: 16 , s: "XVI" },
    { result: 19 , s: "XIX" },
    { result: 20 , s: "XX" },
    { result: 21 , s: "XXI" },
    { result: 24 , s: "XXIV" },
    { result: 25 , s: "XXV" },
    { result: 26 , s: "XXVI" },
    { result: 30 , s: "XXX" },
    { result: 35 , s: "XXXV" },
    { result: 40 , s: "XL" },
    { result: 41 , s: "XLI" },
    { result: 45 , s: "XLV" },
    { result: 49 , s: "XLIX" },
    { result: 50 , s: "L" },
    { result: 51 , s: "LI" },
    { result: 90 , s: "XC" },
    { result: 91 , s: "XCI" },
    { result: 100 , s: "C" },
    { result: 101 , s: "CI" },
    { result: 151 , s: "CLI" },
    { result: 500 , s: "D" },
    { result: 501 , s: "DI" },
    { result: 601 , s: "DCI" },
    { result: 1601 , s: "MDCI" },
    { result: 3749 , s: "MMMDCCXLIX" },
    { result: 58 , s: "LVIII" },
    { result: 1994 , s: "MCMXCIV" },
    { result: 60 , s: "LX" },
  ])("should pass $s  $result", async ({ s, result }) => {
    expect(romanToInt(s)).toStrictEqual(result);
  });
});
